DROP TABLE IF EXISTS TB_HEROS;
CREATE TABLE TB_HEROS(
  ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
  NAME TEXT NOT NULL,
  POWER TEXT NOT NULL
)

-- create
INSERT INTO TB_HEROS(NAME, POWER)
VALUES 
  ('Flash', 'Speed'),
  ('Aquaman', 'Speak with fishes'),
  ('Batman', 'No-one')

--reade
SELECT * FROM TB_HEROS
SELECT * FROM TB_HEROS WHERE NAME='Flash'

--update
UPDATE TB_HEROS
SET NAME = 'Huguinho', POWER='LGL'
WHERE ID = 1

--delete
DELETE FROM TB_HEROS WHERE ID =1
